name: Deploy to www branch
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-build -A wasi
      - name: Copy pokeemerald-randomizer.wasm to www branch
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git fetch origin www
          git checkout www
          cp result/bin/pokeemerald-randomizer.wasm .
          git commit -a --amend --no-edit --quiet && git push --force origin www || true
